### PR TITLE
Ported LWRP RenderPass examples

### PR DESCRIPTION
**Pull request by hybridherbst**
The examples [here ](https://github.com/UnityTechnologies/LWRPScriptableRenderPass_ExampleLibrary)are pretty great and I was always wondering why they're not also in this repo.

Since 7.2.0 is out now I thought it would be a nice opportunity to port them over as WIP samples, so here they are. I [ported ](https://github.com/UnityTechnologies/LWRPScriptableRenderPass_ExampleLibrary/pull/7)them to 2019.3 / URP 7.2.0 and adjusted them for this repo (e.g. automatically loading correct SRP profile on scene load).

20200212-010852_Unity
20200212-010909_Unity
20200212-011010_Unity

They'll need a bit folder structure cleanup, so I added them to the "WIP" section for now.

### CODE REVIEW

**Comment by soraryu** [comment]
@phi-lira do you think you or someone else could over this to merge it in, or tell me what changes are required?

**Comment by andybak** [comment]
Could we at least have a comment from someone at Unity that's either:

1. Yes - we just need to find the time. It's on our to do list
2. Sorry - we'll probably never find the time as we're ultra busy
3. We don't think this should be merged.
4. We might merge but it needs some tweaks

In the absence of 1 to 4 we can only conclude

5. We never look at pull requests

which is a bit disheartening!

**Comment by phi-lira** [comment]
Oh sorry about this. I guess we forgot to review it as we were not added to PR originally. I just added @Verasl but he is out of office now, I'm putting a note to have a chat with him when he's back.

**Comment by hybridherbst** [comment]
Bump!

**Comment by phi-lira** [comment]
Changed this to working branch in our repo. Will take it from there.

**Comment by andybak** [comment]
Apologies if I've overlooked them but there's no mention of the new examples in the readme is there?

I can see that being the crucial entrypoint for someone trying to figure out how to do x in URP.

**Comment by phi-lira** [comment]
I'll have a follow up PR to change the examples, then I'll add wiki pages / changes to README.

**Pull request merged**
